/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DziennikElektroniczny.okna;

import DziennikElektroniczny.modele.ListaPrzedmiotowDlaUczniowModel;
import DziennikElektroniczny.modele.PrzedmiotyComboBoxModel;
import java.sql.*;

/**
 *
 * @author patry
 */
public class OknoOcen extends javax.swing.JFrame {

    /**
     * Creates new form OknoOcen
     */
    private javax.swing.JFrame oknoAplikacji;
    private Connection conn;
    private String uczen;
    private PrzedmiotyComboBoxModel przedmiotyComboBoxModel;

    public OknoOcen(javax.swing.JFrame oknoAplikacji, Connection conn, String uczen, String tytul) {
        initComponents();
        this.oknoAplikacji = oknoAplikacji;
        this.conn = conn;
        this.uczen = uczen;
        setTitle(tytul);
        tytulLabel.setText(tytul.toUpperCase());
        setVisible(true);

        ListaPrzedmiotowDlaUczniowModel listaPrzedmiotowDlaUczniowModel = new ListaPrzedmiotowDlaUczniowModel();
        String[] listaPrzedmiotow = listaPrzedmiotowDlaUczniowModel.listaPrzedmiotow(conn, uczen);
        przedmiotyComboBoxModel = new PrzedmiotyComboBoxModel(listaPrzedmiotow);
        przedmiotyComboBox.setModel(przedmiotyComboBoxModel);
    }

    private OknoOcen() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknoOcenPanel = new javax.swing.JPanel();
        wyjdzOknoOcenButton = new javax.swing.JButton();
        tytulLabel = new javax.swing.JLabel();
        ocenyScrollPane = new javax.swing.JScrollPane();
        ocenyTable = new javax.swing.JTable();
        przedmiotLabel = new javax.swing.JLabel();
        przedmiotyComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Oceny");
        setLocation(new java.awt.Point(550, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        wyjdzOknoOcenButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wyjdzOknoOcenButton.setText("WYJDŹ");
        wyjdzOknoOcenButton.setFocusPainted(false);
        wyjdzOknoOcenButton.setPreferredSize(new java.awt.Dimension(100, 30));
        wyjdzOknoOcenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzOknoOcenButtonActionPerformed(evt);
            }
        });

        tytulLabel.setFont(new java.awt.Font("PT Serif", 1, 24)); // NOI18N
        tytulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tytulLabel.setText("TWOJE OCENY");
        tytulLabel.setPreferredSize(new java.awt.Dimension(300, 30));

        ocenyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ocenyScrollPane.setViewportView(ocenyTable);
        if (ocenyTable.getColumnModel().getColumnCount() > 0) {
            ocenyTable.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            ocenyTable.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            ocenyTable.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            ocenyTable.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        przedmiotLabel.setText("Przedmiot:");

        przedmiotyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout oknoOcenPanelLayout = new javax.swing.GroupLayout(oknoOcenPanel);
        oknoOcenPanel.setLayout(oknoOcenPanelLayout);
        oknoOcenPanelLayout.setHorizontalGroup(
            oknoOcenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoOcenPanelLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(oknoOcenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oknoOcenPanelLayout.createSequentialGroup()
                        .addComponent(przedmiotLabel)
                        .addGap(18, 18, 18)
                        .addComponent(przedmiotyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(oknoOcenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoOcenPanelLayout.createSequentialGroup()
                            .addComponent(wyjdzOknoOcenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(400, 400, 400))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoOcenPanelLayout.createSequentialGroup()
                            .addComponent(ocenyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)))))
            .addGroup(oknoOcenPanelLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(tytulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        oknoOcenPanelLayout.setVerticalGroup(
            oknoOcenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoOcenPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tytulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(oknoOcenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(przedmiotLabel)
                    .addComponent(przedmiotyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(ocenyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wyjdzOknoOcenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoOcenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoOcenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        oknoAplikacji.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void wyjdzOknoOcenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzOknoOcenButtonActionPerformed
        oknoAplikacji.setEnabled(true);
        dispose();
    }//GEN-LAST:event_wyjdzOknoOcenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoOcen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoOcen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoOcen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoOcen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoOcen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ocenyScrollPane;
    private javax.swing.JTable ocenyTable;
    private javax.swing.JPanel oknoOcenPanel;
    private javax.swing.JLabel przedmiotLabel;
    private javax.swing.JComboBox<String> przedmiotyComboBox;
    private javax.swing.JLabel tytulLabel;
    private javax.swing.JButton wyjdzOknoOcenButton;
    // End of variables declaration//GEN-END:variables
}
