/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DziennikElektroniczny.okna;

import DziennikElektroniczny.JDBC;
import DziennikElektroniczny.logowanie.LogowanieNauczyciel;
import DziennikElektroniczny.logowanie.LogowanieRodzic;
import DziennikElektroniczny.logowanie.LogowanieUczen;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author patry
 */
public class OknoAplikacji extends javax.swing.JFrame {

    /**
     * Creates new form OknoLogowania
     */
    private final Connection conn;

    public OknoAplikacji() {
        JDBC jdbc = null;
        try {
            jdbc = new JDBC();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OknoAplikacji.class.getName()).log(Level.SEVERE, null, ex);
        }
        conn = jdbc.getConn();
        initComponents();
        trybUczniaPanel.setVisible(false);
        trybRodzicaPanel.setVisible(false);
        trybNauczycielaPanel.setVisible(false);
        trybDyrektoraPanel.setVisible(false);
        logowaniePanel.setVisible(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPanel = new javax.swing.JPanel();
        uczenButton = new javax.swing.JButton();
        rodzicButton = new javax.swing.JButton();
        nauczycielButton = new javax.swing.JButton();
        dyrektorButton = new javax.swing.JButton();
        zamknijOknoLogowaniaButton = new javax.swing.JButton();
        dziennikElektronicznyLabel = new javax.swing.JLabel();
        logowaniePanel = new javax.swing.JPanel();
        panelLogowanieLabel = new javax.swing.JLabel();
        nazwaUzytkownikaLogowanieLabel = new javax.swing.JLabel();
        nazwaUzytkownikaLogowanieTextField = new javax.swing.JTextField();
        hasloLogowanieLabel = new javax.swing.JLabel();
        hasloLogowaniePasswordField = new javax.swing.JPasswordField();
        zalogujLogowanieButton = new javax.swing.JButton();
        wsteczLogowanieButton = new javax.swing.JButton();
        trybUczniaPanel = new javax.swing.JPanel();
        trybUczniaLabel = new javax.swing.JLabel();
        wyjdzTrybUczniaButton = new javax.swing.JButton();
        trybUczniaZobaczOcenyButton = new javax.swing.JButton();
        trybUczniaZobaczNieobecnosciButton = new javax.swing.JButton();
        trybUczniaZobaczPlanLekcjiButton = new javax.swing.JButton();
        trybRodzicaPanel = new javax.swing.JPanel();
        trybRodzicaLabel = new javax.swing.JLabel();
        wyjdzTrybRodzicaButton = new javax.swing.JButton();
        trybRodzicaZobaczOcenyButton = new javax.swing.JButton();
        trybRodzicaZobaczNieobecnosciButton = new javax.swing.JButton();
        trybRodzicaZobaczPlanLekcjiButton = new javax.swing.JButton();
        trybNauczycielaPanel = new javax.swing.JPanel();
        wyjdzTrybNauczycielaButton = new javax.swing.JButton();
        trybNauczycielaLabel = new javax.swing.JLabel();
        trybNauczycielaZobaczUczniowButton = new javax.swing.JButton();
        trybNauczycielaZobaczPlanLekcjiButton = new javax.swing.JButton();
        trybDyrektoraPanel = new javax.swing.JPanel();
        wyjdzTrybDyrektoraButton = new javax.swing.JButton();
        trybDyrektoraLabel = new javax.swing.JLabel();
        trybDyrektoraZobaczUczniowButton = new javax.swing.JButton();
        trybDyrektoraZobaczKlasyButton = new javax.swing.JButton();
        trybDyrektoraZobaczNauczycieliButton = new javax.swing.JButton();
        trybDyrektoraZobaczListePrzedmiotowButton = new javax.swing.JButton();
        trybDyrektoraPrzydzielPrzedmiotINauczycielaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dziennik Elektroniczny");
        setBackground(new java.awt.Color(51, 51, 255));
        setLocation(new java.awt.Point(700, 200));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setName("oknoLogowania"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        uczenButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uczenButton.setText("UCZEŃ");
        uczenButton.setFocusPainted(false);
        uczenButton.setName("uczenButton"); // NOI18N
        uczenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uczenButtonActionPerformed(evt);
            }
        });

        rodzicButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rodzicButton.setText("RODZIC");
        rodzicButton.setFocusPainted(false);
        rodzicButton.setName("rodzicButton"); // NOI18N
        rodzicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rodzicButtonActionPerformed(evt);
            }
        });

        nauczycielButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nauczycielButton.setText("NAUCZYCIEL");
        nauczycielButton.setFocusPainted(false);
        nauczycielButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nauczycielButton.setName("uczenButton"); // NOI18N
        nauczycielButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nauczycielButtonActionPerformed(evt);
            }
        });

        dyrektorButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dyrektorButton.setText("DYREKTOR");
        dyrektorButton.setFocusPainted(false);
        dyrektorButton.setName("dyrektorButton"); // NOI18N
        dyrektorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dyrektorButtonActionPerformed(evt);
            }
        });

        zamknijOknoLogowaniaButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zamknijOknoLogowaniaButton.setText("Zamknij");
        zamknijOknoLogowaniaButton.setFocusPainted(false);
        zamknijOknoLogowaniaButton.setPreferredSize(new java.awt.Dimension(100, 30));
        zamknijOknoLogowaniaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijOknoLogowaniaButtonActionPerformed(evt);
            }
        });

        dziennikElektronicznyLabel.setFont(new java.awt.Font("Engravers MT", 1, 28)); // NOI18N
        dziennikElektronicznyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dziennikElektronicznyLabel.setText("Dziennik Elektroniczny");
        dziennikElektronicznyLabel.setToolTipText("");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(dziennikElektronicznyLabel)
                .addGap(20, 20, 20))
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dyrektorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(nauczycielButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(rodzicButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(uczenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(zamknijOknoLogowaniaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(dziennikElektronicznyLabel)
                .addGap(83, 83, 83)
                .addComponent(uczenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rodzicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nauczycielButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dyrektorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(zamknijOknoLogowaniaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        logowaniePanel.setMaximumSize(new java.awt.Dimension(600, 600));
        logowaniePanel.setPreferredSize(new java.awt.Dimension(600, 600));

        panelLogowanieLabel.setFont(new java.awt.Font("Engravers MT", 1, 28)); // NOI18N
        panelLogowanieLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelLogowanieLabel.setText("panel ucznia");
        panelLogowanieLabel.setMaximumSize(new java.awt.Dimension(250, 30));
        panelLogowanieLabel.setMinimumSize(new java.awt.Dimension(250, 30));
        panelLogowanieLabel.setPreferredSize(new java.awt.Dimension(250, 30));

        nazwaUzytkownikaLogowanieLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nazwaUzytkownikaLogowanieLabel.setText("Nazwa użytkownika:");

        nazwaUzytkownikaLogowanieTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nazwaUzytkownikaLogowanieTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nazwaUzytkownikaLogowanieTextFieldKeyPressed(evt);
            }
        });

        hasloLogowanieLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hasloLogowanieLabel.setText("Hasło:");

        hasloLogowaniePasswordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hasloLogowaniePasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hasloLogowaniePasswordFieldKeyPressed(evt);
            }
        });

        zalogujLogowanieButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zalogujLogowanieButton.setText("Zaloguj");
        zalogujLogowanieButton.setFocusPainted(false);
        zalogujLogowanieButton.setPreferredSize(new java.awt.Dimension(100, 30));
        zalogujLogowanieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zalogujLogowanieButtonActionPerformed(evt);
            }
        });

        wsteczLogowanieButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wsteczLogowanieButton.setText("Wstecz");
        wsteczLogowanieButton.setFocusPainted(false);
        wsteczLogowanieButton.setPreferredSize(new java.awt.Dimension(100, 30));
        wsteczLogowanieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wsteczLogowanieButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logowaniePanelLayout = new javax.swing.GroupLayout(logowaniePanel);
        logowaniePanel.setLayout(logowaniePanelLayout);
        logowaniePanelLayout.setHorizontalGroup(
            logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logowaniePanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nazwaUzytkownikaLogowanieLabel)
                    .addComponent(hasloLogowanieLabel))
                .addGap(18, 18, 18)
                .addGroup(logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasloLogowaniePasswordField)
                    .addComponent(nazwaUzytkownikaLogowanieTextField))
                .addGap(80, 80, 80))
            .addGroup(logowaniePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(panelLogowanieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logowaniePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wsteczLogowanieButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zalogujLogowanieButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(250, 250, 250))
        );
        logowaniePanelLayout.setVerticalGroup(
            logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logowaniePanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(panelLogowanieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addGroup(logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwaUzytkownikaLogowanieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazwaUzytkownikaLogowanieLabel))
                .addGap(34, 34, 34)
                .addGroup(logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasloLogowaniePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasloLogowanieLabel))
                .addGap(44, 44, 44)
                .addComponent(zalogujLogowanieButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(wsteczLogowanieButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        trybUczniaLabel.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        trybUczniaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trybUczniaLabel.setText("<html><center>witaj w systemie<BR><center>dziennik elektroniczny");
        trybUczniaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        wyjdzTrybUczniaButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wyjdzTrybUczniaButton.setText("Wyloguj");
        wyjdzTrybUczniaButton.setFocusPainted(false);
        wyjdzTrybUczniaButton.setPreferredSize(new java.awt.Dimension(100, 30));
        wyjdzTrybUczniaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzTrybUczniaButtonActionPerformed(evt);
            }
        });

        trybUczniaZobaczOcenyButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybUczniaZobaczOcenyButton.setText("ZOBACZ SWOJE OCENY");
        trybUczniaZobaczOcenyButton.setFocusPainted(false);
        trybUczniaZobaczOcenyButton.setPreferredSize(new java.awt.Dimension(87, 30));
        trybUczniaZobaczOcenyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybUczniaZobaczOcenyButtonActionPerformed(evt);
            }
        });

        trybUczniaZobaczNieobecnosciButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybUczniaZobaczNieobecnosciButton.setText("ZOBACZ SWOJE NIEOBECNOŚCI");
        trybUczniaZobaczNieobecnosciButton.setFocusPainted(false);
        trybUczniaZobaczNieobecnosciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybUczniaZobaczNieobecnosciButtonActionPerformed(evt);
            }
        });

        trybUczniaZobaczPlanLekcjiButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybUczniaZobaczPlanLekcjiButton.setText("ZOBACZ SWÓJ PLAN LEKCJI");
        trybUczniaZobaczPlanLekcjiButton.setFocusPainted(false);
        trybUczniaZobaczPlanLekcjiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybUczniaZobaczPlanLekcjiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trybUczniaPanelLayout = new javax.swing.GroupLayout(trybUczniaPanel);
        trybUczniaPanel.setLayout(trybUczniaPanelLayout);
        trybUczniaPanelLayout.setHorizontalGroup(
            trybUczniaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybUczniaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trybUczniaLabel)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trybUczniaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wyjdzTrybUczniaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(trybUczniaPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(trybUczniaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trybUczniaZobaczPlanLekcjiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trybUczniaZobaczNieobecnosciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trybUczniaZobaczOcenyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        trybUczniaPanelLayout.setVerticalGroup(
            trybUczniaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybUczniaPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(trybUczniaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(trybUczniaZobaczOcenyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trybUczniaZobaczNieobecnosciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trybUczniaZobaczPlanLekcjiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(wyjdzTrybUczniaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        trybRodzicaPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        trybRodzicaLabel.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        trybRodzicaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trybRodzicaLabel.setText("<html><center>witaj w systemie<BR><center>dziennik elektroniczny");
        trybRodzicaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        wyjdzTrybRodzicaButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wyjdzTrybRodzicaButton.setText("Wyloguj");
        wyjdzTrybRodzicaButton.setPreferredSize(new java.awt.Dimension(100, 30));
        wyjdzTrybRodzicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzTrybRodzicaButtonActionPerformed(evt);
            }
        });

        trybRodzicaZobaczOcenyButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybRodzicaZobaczOcenyButton.setText("ZOBACZ OCENY SWOJEGO DZIECKA");
        trybRodzicaZobaczOcenyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybRodzicaZobaczOcenyButtonActionPerformed(evt);
            }
        });

        trybRodzicaZobaczNieobecnosciButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybRodzicaZobaczNieobecnosciButton.setText("ZOBACZ NIEOBECNOŚCI SWOJEGO DZIECKA");
        trybRodzicaZobaczNieobecnosciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybRodzicaZobaczNieobecnosciButtonActionPerformed(evt);
            }
        });

        trybRodzicaZobaczPlanLekcjiButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybRodzicaZobaczPlanLekcjiButton.setText("ZOBACZ PLAN LEKCJI SWOJEGO DZIECKA");
        trybRodzicaZobaczPlanLekcjiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybRodzicaZobaczPlanLekcjiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trybRodzicaPanelLayout = new javax.swing.GroupLayout(trybRodzicaPanel);
        trybRodzicaPanel.setLayout(trybRodzicaPanelLayout);
        trybRodzicaPanelLayout.setHorizontalGroup(
            trybRodzicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybRodzicaPanelLayout.createSequentialGroup()
                .addGroup(trybRodzicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trybRodzicaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(trybRodzicaLabel))
                    .addGroup(trybRodzicaPanelLayout.createSequentialGroup()
                        .addGroup(trybRodzicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(trybRodzicaPanelLayout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(wyjdzTrybRodzicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(trybRodzicaPanelLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(trybRodzicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(trybRodzicaZobaczOcenyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(trybRodzicaZobaczNieobecnosciButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(trybRodzicaZobaczPlanLekcjiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        trybRodzicaPanelLayout.setVerticalGroup(
            trybRodzicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybRodzicaPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(trybRodzicaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(trybRodzicaZobaczOcenyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trybRodzicaZobaczNieobecnosciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trybRodzicaZobaczPlanLekcjiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(wyjdzTrybRodzicaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        trybNauczycielaPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        wyjdzTrybNauczycielaButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wyjdzTrybNauczycielaButton.setText("Wyloguj");
        wyjdzTrybNauczycielaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzTrybNauczycielaButtonActionPerformed(evt);
            }
        });

        trybNauczycielaLabel.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        trybNauczycielaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trybNauczycielaLabel.setText("<html><center>witaj w systemie<BR><center>dziennik elektroniczny");

        trybNauczycielaZobaczUczniowButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybNauczycielaZobaczUczniowButton.setText("ZOBACZ LISTĘ UCZNIÓW");
        trybNauczycielaZobaczUczniowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybNauczycielaZobaczUczniowButtonActionPerformed(evt);
            }
        });

        trybNauczycielaZobaczPlanLekcjiButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybNauczycielaZobaczPlanLekcjiButton.setText("ZOBACZ PLAN LEKCJI");
        trybNauczycielaZobaczPlanLekcjiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybNauczycielaZobaczPlanLekcjiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trybNauczycielaPanelLayout = new javax.swing.GroupLayout(trybNauczycielaPanel);
        trybNauczycielaPanel.setLayout(trybNauczycielaPanelLayout);
        trybNauczycielaPanelLayout.setHorizontalGroup(
            trybNauczycielaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybNauczycielaPanelLayout.createSequentialGroup()
                .addGroup(trybNauczycielaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trybNauczycielaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(trybNauczycielaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
                    .addGroup(trybNauczycielaPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(wyjdzTrybNauczycielaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trybNauczycielaPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(trybNauczycielaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(trybNauczycielaZobaczPlanLekcjiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trybNauczycielaZobaczUczniowButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        trybNauczycielaPanelLayout.setVerticalGroup(
            trybNauczycielaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trybNauczycielaPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(trybNauczycielaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(trybNauczycielaZobaczUczniowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trybNauczycielaZobaczPlanLekcjiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(wyjdzTrybNauczycielaButton)
                .addGap(25, 25, 25))
        );

        wyjdzTrybDyrektoraButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wyjdzTrybDyrektoraButton.setText("Wyloguj");
        wyjdzTrybDyrektoraButton.setPreferredSize(new java.awt.Dimension(100, 30));
        wyjdzTrybDyrektoraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzTrybDyrektoraButtonActionPerformed(evt);
            }
        });

        trybDyrektoraLabel.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        trybDyrektoraLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trybDyrektoraLabel.setText("<html><center>witaj w systemie<BR><center>dziennik elektroniczny");
        trybDyrektoraLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        trybDyrektoraZobaczUczniowButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybDyrektoraZobaczUczniowButton.setText("ZOBACZ LISTĘ UCZNIÓW");
        trybDyrektoraZobaczUczniowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybDyrektoraZobaczUczniowButtonActionPerformed(evt);
            }
        });

        trybDyrektoraZobaczKlasyButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybDyrektoraZobaczKlasyButton.setText("ZOBACZ LISTĘ KLAS");
        trybDyrektoraZobaczKlasyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybDyrektoraZobaczKlasyButtonActionPerformed(evt);
            }
        });

        trybDyrektoraZobaczNauczycieliButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybDyrektoraZobaczNauczycieliButton.setText("ZOBACZ LISTĘ NAUCZYCIELI");
        trybDyrektoraZobaczNauczycieliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybDyrektoraZobaczNauczycieliButtonActionPerformed(evt);
            }
        });

        trybDyrektoraZobaczListePrzedmiotowButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybDyrektoraZobaczListePrzedmiotowButton.setText("ZOBACZ LISTĘ PRZEDMIOTÓW");
        trybDyrektoraZobaczListePrzedmiotowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybDyrektoraZobaczListePrzedmiotowButtonActionPerformed(evt);
            }
        });

        trybDyrektoraPrzydzielPrzedmiotINauczycielaButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trybDyrektoraPrzydzielPrzedmiotINauczycielaButton.setText("PRZYDZIEL PRZEDMIOT I NAUCZYCIELA");
        trybDyrektoraPrzydzielPrzedmiotINauczycielaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trybDyrektoraPrzydzielPrzedmiotINauczycielaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trybDyrektoraPanelLayout = new javax.swing.GroupLayout(trybDyrektoraPanel);
        trybDyrektoraPanel.setLayout(trybDyrektoraPanelLayout);
        trybDyrektoraPanelLayout.setHorizontalGroup(
            trybDyrektoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybDyrektoraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trybDyrektoraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(trybDyrektoraPanelLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(wyjdzTrybDyrektoraButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trybDyrektoraPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(trybDyrektoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(trybDyrektoraPrzydzielPrzedmiotINauczycielaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(trybDyrektoraZobaczListePrzedmiotowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trybDyrektoraZobaczKlasyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(trybDyrektoraZobaczNauczycieliButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(trybDyrektoraZobaczUczniowButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        trybDyrektoraPanelLayout.setVerticalGroup(
            trybDyrektoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trybDyrektoraPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(trybDyrektoraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(trybDyrektoraZobaczUczniowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trybDyrektoraZobaczKlasyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trybDyrektoraZobaczNauczycieliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trybDyrektoraZobaczListePrzedmiotowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trybDyrektoraPrzydzielPrzedmiotINauczycielaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(wyjdzTrybDyrektoraButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybUczniaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybRodzicaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybNauczycielaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybDyrektoraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(logowaniePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybUczniaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybRodzicaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybNauczycielaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybDyrektoraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(logowaniePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void zStartDoLogowanie(String tekst) {
        startPanel.setVisible(false);
        panelLogowanieLabel.setText(tekst);
        nazwaUzytkownikaLogowanieTextField.setText("");
        hasloLogowaniePasswordField.setText("");
        logowaniePanel.setVisible(true);
    }

    private void uczenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uczenButtonActionPerformed
        zStartDoLogowanie("panel ucznia");
    }//GEN-LAST:event_uczenButtonActionPerformed

    private void rodzicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rodzicButtonActionPerformed
        zStartDoLogowanie("panel rodzica");
    }//GEN-LAST:event_rodzicButtonActionPerformed

    private void nauczycielButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nauczycielButtonActionPerformed
        zStartDoLogowanie("panel nauczyciela");
    }//GEN-LAST:event_nauczycielButtonActionPerformed

    private void dyrektorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dyrektorButtonActionPerformed
        zStartDoLogowanie("panel dyrektora");
    }//GEN-LAST:event_dyrektorButtonActionPerformed

    private void zamknijOknoLogowaniaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijOknoLogowaniaButtonActionPerformed
        try {
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(OknoAplikacji.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Odłączono od bazy danych");
        dispose();
    }//GEN-LAST:event_zamknijOknoLogowaniaButtonActionPerformed

    private void wyjdzTrybNauczycielaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzTrybNauczycielaButtonActionPerformed
        trybNauczycielaPanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_wyjdzTrybNauczycielaButtonActionPerformed

    private void zalogujLogowanieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zalogujLogowanieButtonActionPerformed
        if (panelLogowanieLabel.getText().equals("panel ucznia")) {
            LogowanieUczen logowanieUczen = new LogowanieUczen(conn, nazwaUzytkownikaLogowanieTextField.getText(), hasloLogowaniePasswordField.getText());
            if (logowanieUczen.zaloguj()) {
                logowaniePanel.setVisible(false);
                trybUczniaPanel.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Błędna nazwa użytkownika lub błędne hasło", "Błąd logowania", JOptionPane.ERROR_MESSAGE);
            }
        } else if ((panelLogowanieLabel.getText().equals("panel rodzica"))) {
            LogowanieRodzic logowanieRodzic = new LogowanieRodzic(conn, nazwaUzytkownikaLogowanieTextField.getText(), hasloLogowaniePasswordField.getText());
            if (logowanieRodzic.zaloguj()) {
                logowaniePanel.setVisible(false);
                trybRodzicaPanel.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Błędna nazwa użytkownika lub błędne hasło", "Błąd logowania", JOptionPane.ERROR_MESSAGE);
            }
        } else if ((panelLogowanieLabel.getText().equals("panel nauczyciela"))) {
            LogowanieNauczyciel logowanieNauczyciel = new LogowanieNauczyciel(conn, nazwaUzytkownikaLogowanieTextField.getText(), hasloLogowaniePasswordField.getText());
            if (logowanieNauczyciel.zaloguj()) {
                logowaniePanel.setVisible(false);
                trybNauczycielaPanel.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Błędna nazwa użytkownika lub błędne hasło", "Błąd logowania", JOptionPane.ERROR_MESSAGE);
            }
        } else if ((panelLogowanieLabel.getText().equals("panel dyrektora") && nazwaUzytkownikaLogowanieTextField.getText().equals("dyrektor") && hasloLogowaniePasswordField.getText().equals("dyrektor"))) {
            logowaniePanel.setVisible(false);
            trybDyrektoraPanel.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Błędna nazwa użytkownika lub błędne hasło", "Błąd logowania", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_zalogujLogowanieButtonActionPerformed

    private void wsteczLogowanieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wsteczLogowanieButtonActionPerformed
        logowaniePanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_wsteczLogowanieButtonActionPerformed

    private void hasloLogowaniePasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hasloLogowaniePasswordFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            zalogujLogowanieButtonActionPerformed(null);
        }
    }//GEN-LAST:event_hasloLogowaniePasswordFieldKeyPressed

    private void wyjdzTrybUczniaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzTrybUczniaButtonActionPerformed
        trybUczniaPanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_wyjdzTrybUczniaButtonActionPerformed

    private void wyjdzTrybDyrektoraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzTrybDyrektoraButtonActionPerformed
        trybDyrektoraPanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_wyjdzTrybDyrektoraButtonActionPerformed

    private void wyjdzTrybRodzicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzTrybRodzicaButtonActionPerformed
        trybRodzicaPanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_wyjdzTrybRodzicaButtonActionPerformed

    private void trybUczniaZobaczOcenyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybUczniaZobaczOcenyButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoOcen oknoOcen = new OknoOcen(this);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybUczniaZobaczOcenyButtonActionPerformed

    private void trybUczniaZobaczNieobecnosciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybUczniaZobaczNieobecnosciButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoNieobecnosci oknoNieobecnosci = new OknoNieobecnosci(this);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybUczniaZobaczNieobecnosciButtonActionPerformed

    private void trybUczniaZobaczPlanLekcjiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybUczniaZobaczPlanLekcjiButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoPlanuLekcji oknoPlanuLekcji = new OknoPlanuLekcji(this);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybUczniaZobaczPlanLekcjiButtonActionPerformed

    private void nazwaUzytkownikaLogowanieTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nazwaUzytkownikaLogowanieTextFieldKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            zalogujLogowanieButtonActionPerformed(null);
        }
    }//GEN-LAST:event_nazwaUzytkownikaLogowanieTextFieldKeyPressed

    private void trybRodzicaZobaczOcenyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybRodzicaZobaczOcenyButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoOcen oknoOcen = new OknoOcen(this);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybRodzicaZobaczOcenyButtonActionPerformed

    private void trybRodzicaZobaczNieobecnosciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybRodzicaZobaczNieobecnosciButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoNieobecnosci oknoNieobecnosci = new OknoNieobecnosci(this);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybRodzicaZobaczNieobecnosciButtonActionPerformed

    private void trybRodzicaZobaczPlanLekcjiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybRodzicaZobaczPlanLekcjiButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoPlanuLekcji oknoPlanuLekcji = new OknoPlanuLekcji(this);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybRodzicaZobaczPlanLekcjiButtonActionPerformed

    private void trybNauczycielaZobaczUczniowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybNauczycielaZobaczUczniowButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoListyKlas oknoList = new OknoListyKlas(this, conn);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybNauczycielaZobaczUczniowButtonActionPerformed

    private void trybNauczycielaZobaczPlanLekcjiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybNauczycielaZobaczPlanLekcjiButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoPlanuLekcji oknoPlanuLekcji = new OknoPlanuLekcji(this);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybNauczycielaZobaczPlanLekcjiButtonActionPerformed

    private void trybDyrektoraZobaczUczniowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybDyrektoraZobaczUczniowButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoListyUczniow oknoListyUczniow = new OknoListyUczniow(this, conn);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybDyrektoraZobaczUczniowButtonActionPerformed

    private void trybDyrektoraZobaczKlasyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybDyrektoraZobaczKlasyButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoListyKlas oknoListyKlas = new OknoListyKlas(this, conn);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybDyrektoraZobaczKlasyButtonActionPerformed

    private void trybDyrektoraZobaczNauczycieliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybDyrektoraZobaczNauczycieliButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoListyNauczycieli oknoListyNauczycieli = new OknoListyNauczycieli(this, conn);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybDyrektoraZobaczNauczycieliButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(OknoAplikacji.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Odłączono od bazy danych");
    }//GEN-LAST:event_formWindowClosing

    private void trybDyrektoraZobaczListePrzedmiotowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybDyrektoraZobaczListePrzedmiotowButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoListyPrzedmiotow oknoListyPrzedmiotow = new OknoListyPrzedmiotow(this, conn);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybDyrektoraZobaczListePrzedmiotowButtonActionPerformed

    private void trybDyrektoraPrzydzielPrzedmiotINauczycielaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trybDyrektoraPrzydzielPrzedmiotINauczycielaButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoListyPrzydzialow oknoListyPrzydzialow = new OknoListyPrzydzialow(this, conn);
        });
        setEnabled(false);
    }//GEN-LAST:event_trybDyrektoraPrzydzielPrzedmiotINauczycielaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoAplikacji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dyrektorButton;
    private javax.swing.JLabel dziennikElektronicznyLabel;
    private javax.swing.JLabel hasloLogowanieLabel;
    private javax.swing.JPasswordField hasloLogowaniePasswordField;
    private javax.swing.JPanel logowaniePanel;
    private javax.swing.JButton nauczycielButton;
    private javax.swing.JLabel nazwaUzytkownikaLogowanieLabel;
    private javax.swing.JTextField nazwaUzytkownikaLogowanieTextField;
    private javax.swing.JLabel panelLogowanieLabel;
    private javax.swing.JButton rodzicButton;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLabel trybDyrektoraLabel;
    private javax.swing.JPanel trybDyrektoraPanel;
    private javax.swing.JButton trybDyrektoraPrzydzielPrzedmiotINauczycielaButton;
    private javax.swing.JButton trybDyrektoraZobaczKlasyButton;
    private javax.swing.JButton trybDyrektoraZobaczListePrzedmiotowButton;
    private javax.swing.JButton trybDyrektoraZobaczNauczycieliButton;
    private javax.swing.JButton trybDyrektoraZobaczUczniowButton;
    private javax.swing.JLabel trybNauczycielaLabel;
    private javax.swing.JPanel trybNauczycielaPanel;
    private javax.swing.JButton trybNauczycielaZobaczPlanLekcjiButton;
    private javax.swing.JButton trybNauczycielaZobaczUczniowButton;
    private javax.swing.JLabel trybRodzicaLabel;
    private javax.swing.JPanel trybRodzicaPanel;
    private javax.swing.JButton trybRodzicaZobaczNieobecnosciButton;
    private javax.swing.JButton trybRodzicaZobaczOcenyButton;
    private javax.swing.JButton trybRodzicaZobaczPlanLekcjiButton;
    private javax.swing.JLabel trybUczniaLabel;
    private javax.swing.JPanel trybUczniaPanel;
    private javax.swing.JButton trybUczniaZobaczNieobecnosciButton;
    private javax.swing.JButton trybUczniaZobaczOcenyButton;
    private javax.swing.JButton trybUczniaZobaczPlanLekcjiButton;
    private javax.swing.JButton uczenButton;
    private javax.swing.JButton wsteczLogowanieButton;
    private javax.swing.JButton wyjdzTrybDyrektoraButton;
    private javax.swing.JButton wyjdzTrybNauczycielaButton;
    private javax.swing.JButton wyjdzTrybRodzicaButton;
    private javax.swing.JButton wyjdzTrybUczniaButton;
    private javax.swing.JButton zalogujLogowanieButton;
    private javax.swing.JButton zamknijOknoLogowaniaButton;
    // End of variables declaration//GEN-END:variables
}
