/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DziennikElektroniczny.okna;

import DziennikElektroniczny.modele.OcenyTableModel;
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author patry
 */
public class OknoSzczegolow extends javax.swing.JFrame {

    /**
     * Creates new form OknoSzczegolow
     */
    private javax.swing.JFrame oknoLekcji;
    private Connection conn;
    private String idUcznia;
    private String przedmiot;
    private String uczen;
    private OcenyTableModel ocenyTableModel;

    public OknoSzczegolow(javax.swing.JFrame oknoLekcji, Connection conn, String idUcznia, String klasaIPrzedmiot, String uczen) {
        this.oknoLekcji = oknoLekcji;
        this.conn = conn;
        this.idUcznia = idUcznia;
        String[] przedmiot = klasaIPrzedmiot.split("[|]");
        this.przedmiot = przedmiot[1].substring(1);
        this.uczen = uczen;

        initComponents();

        ocenyTableModel = new OcenyTableModel(conn, idUcznia, this.przedmiot, "nauczyciel");
        ocenyTableModel.fireTableDataChanged();
        ocenyTable.setModel(ocenyTableModel);
        ocenyTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ocenyTable.getTableHeader().setReorderingAllowed(false);

        setVisible(true);
    }

    private OknoSzczegolow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknoSzczegolowPanel = new javax.swing.JPanel();
        tytulLabel = new javax.swing.JLabel();
        zamknijButton = new javax.swing.JButton();
        ocenyScrollPane = new javax.swing.JScrollPane();
        ocenyTable = new javax.swing.JTable();
        opcjePanel = new javax.swing.JPanel();
        poprawOceneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Szczegóły ucznia");
        setLocation(new java.awt.Point(550, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tytulLabel.setFont(new java.awt.Font("PT Serif", 1, 24)); // NOI18N
        tytulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tytulLabel.setText("SZCZEGÓŁY UCZNIA");

        zamknijButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        zamknijButton.setText("ZAMKNIJ");
        zamknijButton.setPreferredSize(new java.awt.Dimension(100, 30));
        zamknijButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijButtonActionPerformed(evt);
            }
        });

        ocenyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ocenyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ocenyTableMousePressed(evt);
            }
        });
        ocenyScrollPane.setViewportView(ocenyTable);

        poprawOceneButton.setText("Popraw ocenę");
        poprawOceneButton.setEnabled(false);
        poprawOceneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poprawOceneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcjePanelLayout = new javax.swing.GroupLayout(opcjePanel);
        opcjePanel.setLayout(opcjePanelLayout);
        opcjePanelLayout.setHorizontalGroup(
            opcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(poprawOceneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        opcjePanelLayout.setVerticalGroup(
            opcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcjePanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(poprawOceneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout oknoSzczegolowPanelLayout = new javax.swing.GroupLayout(oknoSzczegolowPanel);
        oknoSzczegolowPanel.setLayout(oknoSzczegolowPanelLayout);
        oknoSzczegolowPanelLayout.setHorizontalGroup(
            oknoSzczegolowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoSzczegolowPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tytulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(oknoSzczegolowPanelLayout.createSequentialGroup()
                .addGroup(oknoSzczegolowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oknoSzczegolowPanelLayout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(zamknijButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(oknoSzczegolowPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ocenyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(opcjePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        oknoSzczegolowPanelLayout.setVerticalGroup(
            oknoSzczegolowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknoSzczegolowPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tytulLabel)
                .addGap(85, 85, 85)
                .addGroup(oknoSzczegolowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcjePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ocenyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(zamknijButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoSzczegolowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoSzczegolowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        oknoLekcji.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void zamknijButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijButtonActionPerformed
        oknoLekcji.setEnabled(true);
        dispose();
    }//GEN-LAST:event_zamknijButtonActionPerformed

    private void ocenyTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocenyTableMousePressed
        if (evt.getButton() == MouseEvent.BUTTON1) {
            poprawOceneButton.setEnabled(true);
        }
    }//GEN-LAST:event_ocenyTableMousePressed

    private void poprawOceneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poprawOceneButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoPoprawyOceny oknoPoprawyOceny = new OknoPoprawyOceny(this, conn, uczen, ocenyTable.getValueAt(ocenyTable.getSelectedRow(), 3).toString(),
                    ocenyTable.getValueAt(ocenyTable.getSelectedRow(), 1).toString(), ocenyTable.getValueAt(ocenyTable.getSelectedRow(), 0).toString(),
                    ocenyTable.getValueAt(ocenyTable.getSelectedRow(), 2).toString(), ocenyTableModel, ocenyTable, przedmiot, poprawOceneButton, idUcznia);
        });
        setEnabled(false);
    }//GEN-LAST:event_poprawOceneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoSzczegolow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoSzczegolow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoSzczegolow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoSzczegolow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoSzczegolow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ocenyScrollPane;
    private javax.swing.JTable ocenyTable;
    private javax.swing.JPanel oknoSzczegolowPanel;
    private javax.swing.JPanel opcjePanel;
    private javax.swing.JButton poprawOceneButton;
    private javax.swing.JLabel tytulLabel;
    private javax.swing.JButton zamknijButton;
    // End of variables declaration//GEN-END:variables
}
