/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DziennikElektroniczny.okna;

import DziennikElektroniczny.modele.OcenyTableModel;
import DziennikElektroniczny.modele.UczniowieDlaNauczycieliTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author patry
 */
public class OknoOceny extends javax.swing.JFrame {

    /**
     * Creates new form OknoOceny
     */
    private javax.swing.JFrame oknoLekcji;
    private final Connection conn;
    private UczniowieDlaNauczycieliTableModel uczniowieDlaNauczycieliTableModel;
    private javax.swing.JTable uczniowieDlaNauczycieliTable;
    private String przedmiot;
    private String idLekcji;

    public OknoOceny(javax.swing.JFrame oknoLekcji, Connection conn, UczniowieDlaNauczycieliTableModel uczniowieDlaNauczycieliTableModel,
            javax.swing.JTable uczniowieDlaNauczycieliTable, String wybranaLekcja, String klasaIPrzedmiot) {
        this.oknoLekcji = oknoLekcji;
        this.conn = conn;
        this.uczniowieDlaNauczycieliTableModel = uczniowieDlaNauczycieliTableModel;
        this.uczniowieDlaNauczycieliTable = uczniowieDlaNauczycieliTable;
        String[] klasaPrzedmiot = klasaIPrzedmiot.split("[|]");
        this.przedmiot = klasaPrzedmiot[1].substring(1);
        System.out.println(this.przedmiot);
        String[] idLekcji = wybranaLekcja.split("ID: ");
        this.idLekcji = idLekcji[1];
        initComponents();
        uczenTextField.setText(((String) uczniowieDlaNauczycieliTable.getValueAt(uczniowieDlaNauczycieliTable.getSelectedRow(), 0))
                + " " + ((String) uczniowieDlaNauczycieliTable.getValueAt(uczniowieDlaNauczycieliTable.getSelectedRow(), 1)));
        String[] numerLekcji = wybranaLekcja.split("[.]");
        lekcjaTextField.setText(numerLekcji[0]);
        setVisible(true);
    }

    private OknoOceny() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknoOcenyPanel = new javax.swing.JPanel();
        tytulLabel = new javax.swing.JLabel();
        uczenLabel = new javax.swing.JLabel();
        lekcjaLabel = new javax.swing.JLabel();
        stopienLabel = new javax.swing.JLabel();
        stopienTextField = new javax.swing.JTextField();
        wagaLabel = new javax.swing.JLabel();
        wagaTextField = new javax.swing.JTextField();
        typLabel = new javax.swing.JLabel();
        typTextField = new javax.swing.JTextField();
        wstawButton = new javax.swing.JButton();
        anulujButton = new javax.swing.JButton();
        uczenTextField = new javax.swing.JTextField();
        lekcjaTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wstaw ocenę");
        setLocation(new java.awt.Point(800, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tytulLabel.setFont(new java.awt.Font("PT Serif", 1, 18)); // NOI18N
        tytulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tytulLabel.setText("WSTAW OCENĘ");

        uczenLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uczenLabel.setText("Uczeń:");

        lekcjaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lekcjaLabel.setText("Lekcja:");

        stopienLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stopienLabel.setText("Stopień:");

        wagaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wagaLabel.setText("Waga:");

        typLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        typLabel.setText("Typ:");

        wstawButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        wstawButton.setText("WSTAW");
        wstawButton.setPreferredSize(new java.awt.Dimension(100, 30));
        wstawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wstawButtonActionPerformed(evt);
            }
        });

        anulujButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        anulujButton.setText("ANULUJ");
        anulujButton.setPreferredSize(new java.awt.Dimension(100, 30));
        anulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujButtonActionPerformed(evt);
            }
        });

        uczenTextField.setEditable(false);

        lekcjaTextField.setEditable(false);

        javax.swing.GroupLayout oknoOcenyPanelLayout = new javax.swing.GroupLayout(oknoOcenyPanel);
        oknoOcenyPanel.setLayout(oknoOcenyPanelLayout);
        oknoOcenyPanelLayout.setHorizontalGroup(
            oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknoOcenyPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(wstawButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(anulujButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoOcenyPanelLayout.createSequentialGroup()
                .addGroup(oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(oknoOcenyPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(uczenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lekcjaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(wagaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(stopienLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(typLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wagaTextField)
                            .addComponent(stopienTextField)
                            .addComponent(typTextField)
                            .addComponent(uczenTextField)
                            .addComponent(lekcjaTextField)))
                    .addGroup(oknoOcenyPanelLayout.createSequentialGroup()
                        .addContainerGap(50, Short.MAX_VALUE)
                        .addComponent(tytulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        oknoOcenyPanelLayout.setVerticalGroup(
            oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknoOcenyPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tytulLabel)
                .addGap(18, 18, 18)
                .addGroup(oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uczenLabel)
                    .addComponent(uczenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lekcjaLabel)
                    .addComponent(lekcjaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopienLabel)
                    .addComponent(stopienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wagaLabel)
                    .addComponent(wagaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typLabel)
                    .addComponent(typTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(oknoOcenyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wstawButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anulujButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoOcenyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoOcenyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        oknoLekcji.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void anulujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujButtonActionPerformed
        oknoLekcji.setEnabled(true);
        dispose();
    }//GEN-LAST:event_anulujButtonActionPerformed

    private void wstawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wstawButtonActionPerformed
        String idUcznia = uczniowieDlaNauczycieliTableModel.getIdUcznia(uczniowieDlaNauczycieliTable.getSelectedRow());
        OcenyTableModel ocenyTableModel = new OcenyTableModel(conn, idUcznia, przedmiot, "nauczyciel");
        try {
            ocenyTableModel.wstawOcene(stopienTextField.getText(), typTextField.getText(), wagaTextField.getText(), idLekcji,
                    uczniowieDlaNauczycieliTableModel.getIdUcznia(uczniowieDlaNauczycieliTable.getSelectedRow()));
        } catch (SQLException ex) {
            Logger.getLogger(OknoOceny.class.getName()).log(Level.SEVERE, null, ex);
        }
        oknoLekcji.setEnabled(true);
        dispose();
    }//GEN-LAST:event_wstawButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoOceny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoOceny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoOceny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoOceny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoOceny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anulujButton;
    private javax.swing.JLabel lekcjaLabel;
    private javax.swing.JTextField lekcjaTextField;
    private javax.swing.JPanel oknoOcenyPanel;
    private javax.swing.JLabel stopienLabel;
    private javax.swing.JTextField stopienTextField;
    private javax.swing.JLabel typLabel;
    private javax.swing.JTextField typTextField;
    private javax.swing.JLabel tytulLabel;
    private javax.swing.JLabel uczenLabel;
    private javax.swing.JTextField uczenTextField;
    private javax.swing.JLabel wagaLabel;
    private javax.swing.JTextField wagaTextField;
    private javax.swing.JButton wstawButton;
    // End of variables declaration//GEN-END:variables
}
