/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DziennikElektroniczny.okna;

import DziennikElektroniczny.modele.ComboBoxModel;
import DziennikElektroniczny.modele.ListaPrzedmiotowDlaUczniowModel;
import DziennikElektroniczny.modele.ObecnosciTableModel;
import java.sql.*;
import javax.swing.ListSelectionModel;

/**
 *
 * @author patry
 */
public class OknoObecnosci extends javax.swing.JFrame {

    /**
     * Creates new form OknoObecnosci
     */
    private javax.swing.JFrame oknoAplikacji;
    private Connection conn;
    private String uczen;
    private ComboBoxModel przedmiotyComboBoxModel;
    private ObecnosciTableModel obecnosciTableModel;

    public OknoObecnosci(javax.swing.JFrame oknoAplikacji, Connection conn, String uczen, String tytul) {
        initComponents();
        this.oknoAplikacji = oknoAplikacji;
        this.conn = conn;
        this.uczen = uczen;
        setTitle(tytul);
        tytulLabel.setText(tytul.toUpperCase());
        setVisible(true);

        ListaPrzedmiotowDlaUczniowModel listaPrzedmiotowDlaUczniowModel = new ListaPrzedmiotowDlaUczniowModel();
        String[] listaPrzedmiotow = listaPrzedmiotowDlaUczniowModel.listaPrzedmiotow(conn, uczen);
        przedmiotyComboBoxModel = new ComboBoxModel(listaPrzedmiotow);
        przedmiotyComboBox.setModel(przedmiotyComboBoxModel);

        obecnosciTableModel = new ObecnosciTableModel(conn, uczen, przedmiotyComboBox.getSelectedItem().toString());
        obecnosciTableModel.fireTableDataChanged();
        obecnosciTable.setModel(obecnosciTableModel);
        obecnosciTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        obecnosciTable.getTableHeader().setReorderingAllowed(false);
    }

    private OknoObecnosci() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknoNieobecnosciPanel = new javax.swing.JPanel();
        wyjdzOknoNieobecnosciButton = new javax.swing.JButton();
        tytulLabel = new javax.swing.JLabel();
        obecnosciScrollPane = new javax.swing.JScrollPane();
        obecnosciTable = new javax.swing.JTable();
        przedmiotLabel = new javax.swing.JLabel();
        przedmiotyComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nieobecności");
        setLocation(new java.awt.Point(550, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        oknoNieobecnosciPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        wyjdzOknoNieobecnosciButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wyjdzOknoNieobecnosciButton.setText("WYJDŹ");
        wyjdzOknoNieobecnosciButton.setFocusPainted(false);
        wyjdzOknoNieobecnosciButton.setPreferredSize(new java.awt.Dimension(100, 30));
        wyjdzOknoNieobecnosciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzOknoNieobecnosciButtonActionPerformed(evt);
            }
        });

        tytulLabel.setFont(new java.awt.Font("PT Serif", 1, 24)); // NOI18N
        tytulLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tytulLabel.setText("TWÓJ STAN OBECNOŚCI");
        tytulLabel.setPreferredSize(new java.awt.Dimension(300, 30));

        obecnosciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        obecnosciScrollPane.setViewportView(obecnosciTable);

        przedmiotLabel.setText("Przedmiot:");

        przedmiotyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        przedmiotyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przedmiotyComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout oknoNieobecnosciPanelLayout = new javax.swing.GroupLayout(oknoNieobecnosciPanel);
        oknoNieobecnosciPanel.setLayout(oknoNieobecnosciPanelLayout);
        oknoNieobecnosciPanelLayout.setHorizontalGroup(
            oknoNieobecnosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoNieobecnosciPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wyjdzOknoNieobecnosciButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
            .addGroup(oknoNieobecnosciPanelLayout.createSequentialGroup()
                .addGroup(oknoNieobecnosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oknoNieobecnosciPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(oknoNieobecnosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obecnosciScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(oknoNieobecnosciPanelLayout.createSequentialGroup()
                                .addComponent(przedmiotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(przedmiotyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(oknoNieobecnosciPanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(tytulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        oknoNieobecnosciPanelLayout.setVerticalGroup(
            oknoNieobecnosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoNieobecnosciPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tytulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(oknoNieobecnosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(przedmiotLabel)
                    .addComponent(przedmiotyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(obecnosciScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(wyjdzOknoNieobecnosciButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoNieobecnosciPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoNieobecnosciPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wyjdzOknoNieobecnosciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzOknoNieobecnosciButtonActionPerformed
        oknoAplikacji.setEnabled(true);
        dispose();
    }//GEN-LAST:event_wyjdzOknoNieobecnosciButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        oknoAplikacji.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void przedmiotyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przedmiotyComboBoxActionPerformed
        obecnosciTableModel = new ObecnosciTableModel(conn, uczen, przedmiotyComboBox.getSelectedItem().toString());
        obecnosciTableModel.fireTableDataChanged();
        obecnosciTable.setModel(obecnosciTableModel);
    }//GEN-LAST:event_przedmiotyComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoObecnosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoObecnosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoObecnosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoObecnosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoObecnosci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane obecnosciScrollPane;
    private javax.swing.JTable obecnosciTable;
    private javax.swing.JPanel oknoNieobecnosciPanel;
    private javax.swing.JLabel przedmiotLabel;
    private javax.swing.JComboBox<String> przedmiotyComboBox;
    private javax.swing.JLabel tytulLabel;
    private javax.swing.JButton wyjdzOknoNieobecnosciButton;
    // End of variables declaration//GEN-END:variables
}
