/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DziennikElektroniczny.okna;

import DziennikElektroniczny.modele.ListaKlasModel;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author patry
 */
public class OknoKlasy extends javax.swing.JFrame {

    /**
     * Creates new form OknoKlasy
     */
    private javax.swing.JFrame oknoListyKlas;
    private final Connection conn;
    private ListaKlasModel listaKlasModel;
    private javax.swing.JTable klasyTable;

    public OknoKlasy(javax.swing.JFrame oknoListyKlas, Connection connection, ListaKlasModel listaKlasModel, javax.swing.JTable klasyTable) {
        conn = connection;
        this.oknoListyKlas = oknoListyKlas;
        this.listaKlasModel = listaKlasModel;
        this.klasyTable = klasyTable;
        
        initComponents();
        setTitle("Dodaj nową klasę");
        setVisible(true);
    }

    private OknoKlasy() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknoKlasyPanel = new javax.swing.JPanel();
        dodajNowaKlaseLabel = new javax.swing.JLabel();
        anulujOknoKlasyButton = new javax.swing.JButton();
        dodajOknoKlasyButton = new javax.swing.JButton();
        nazwaOknoKlasyLabel = new javax.swing.JLabel();
        rokPowstaniaOknoKlasyLabel = new javax.swing.JLabel();
        profilOknoKlasyLabel = new javax.swing.JLabel();
        nazwaOknoKlasyTextField = new javax.swing.JTextField();
        rokPowstaniaOknoKlasyTextField = new javax.swing.JTextField();
        profilOknoKlasyTextField = new javax.swing.JTextField();
        obowiazkoweNazwaLabel = new javax.swing.JLabel();
        obowiazkoweRokPowstaniaLabel = new javax.swing.JLabel();
        obowiazkoweProfilLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(800, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        dodajNowaKlaseLabel.setFont(new java.awt.Font("PT Serif", 1, 18)); // NOI18N
        dodajNowaKlaseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dodajNowaKlaseLabel.setText("DODAJ NOWĄ KLASĘ");

        anulujOknoKlasyButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        anulujOknoKlasyButton.setText("ANULUJ");
        anulujOknoKlasyButton.setPreferredSize(new java.awt.Dimension(100, 30));
        anulujOknoKlasyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujOknoKlasyButtonActionPerformed(evt);
            }
        });

        dodajOknoKlasyButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dodajOknoKlasyButton.setText("DODAJ");
        dodajOknoKlasyButton.setPreferredSize(new java.awt.Dimension(100, 30));
        dodajOknoKlasyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajOknoKlasyButtonActionPerformed(evt);
            }
        });

        nazwaOknoKlasyLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nazwaOknoKlasyLabel.setText("Nazwa:");

        rokPowstaniaOknoKlasyLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rokPowstaniaOknoKlasyLabel.setText("Rok powstania:");

        profilOknoKlasyLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        profilOknoKlasyLabel.setText("Profil:");

        obowiazkoweNazwaLabel.setText("*");

        obowiazkoweRokPowstaniaLabel.setText("*");

        obowiazkoweProfilLabel.setText("*");

        javax.swing.GroupLayout oknoKlasyPanelLayout = new javax.swing.GroupLayout(oknoKlasyPanel);
        oknoKlasyPanel.setLayout(oknoKlasyPanelLayout);
        oknoKlasyPanelLayout.setHorizontalGroup(
            oknoKlasyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknoKlasyPanelLayout.createSequentialGroup()
                .addGroup(oknoKlasyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oknoKlasyPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(dodajNowaKlaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(oknoKlasyPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(dodajOknoKlasyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(anulujOknoKlasyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(oknoKlasyPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(oknoKlasyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nazwaOknoKlasyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profilOknoKlasyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rokPowstaniaOknoKlasyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(oknoKlasyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rokPowstaniaOknoKlasyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profilOknoKlasyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazwaOknoKlasyTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(oknoKlasyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obowiazkoweNazwaLabel)
                            .addComponent(obowiazkoweRokPowstaniaLabel)
                            .addComponent(obowiazkoweProfilLabel))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        oknoKlasyPanelLayout.setVerticalGroup(
            oknoKlasyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknoKlasyPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(dodajNowaKlaseLabel)
                .addGap(30, 30, 30)
                .addGroup(oknoKlasyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwaOknoKlasyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazwaOknoKlasyLabel)
                    .addComponent(obowiazkoweNazwaLabel))
                .addGap(18, 18, 18)
                .addGroup(oknoKlasyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oknoKlasyPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(rokPowstaniaOknoKlasyLabel))
                    .addGroup(oknoKlasyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rokPowstaniaOknoKlasyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(obowiazkoweRokPowstaniaLabel)))
                .addGap(18, 18, 18)
                .addGroup(oknoKlasyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profilOknoKlasyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilOknoKlasyLabel)
                    .addComponent(obowiazkoweProfilLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(oknoKlasyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dodajOknoKlasyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anulujOknoKlasyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(oknoKlasyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoKlasyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        oknoListyKlas.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void anulujOknoKlasyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujOknoKlasyButtonActionPerformed
        oknoListyKlas.setEnabled(true);
        dispose();
    }//GEN-LAST:event_anulujOknoKlasyButtonActionPerformed

    private void dodajOknoKlasyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajOknoKlasyButtonActionPerformed
        boolean czyWypelniono = true;
        String czegoBrakuje = "Nie wypełniono następujących obowiązkowych pól:\n";
        if (nazwaOknoKlasyTextField.getText().isEmpty()) {
            czyWypelniono = false;
            czegoBrakuje += "Nazwa\n";
        }
        if (rokPowstaniaOknoKlasyTextField.getText().isEmpty()) {
            czyWypelniono = false;
            czegoBrakuje += "Rok powstania\n";
        }
        if (profilOknoKlasyTextField.getText().isEmpty()) {
            czyWypelniono = false;
            czegoBrakuje += "Profil\n";
        }
        if (czyWypelniono) {
            try {
                listaKlasModel.insertRow(
                        nazwaOknoKlasyTextField.getText(),
                        rokPowstaniaOknoKlasyTextField.getText(),
                        profilOknoKlasyTextField.getText(),
                        0);
            } catch (SQLException ex) {
                Logger.getLogger(OknoKlasy.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                listaKlasModel = new ListaKlasModel(conn);
                listaKlasModel.fireTableDataChanged();
                klasyTable.setModel(listaKlasModel);
                oknoListyKlas.setEnabled(true);
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, czegoBrakuje + "Proszę je uzupełnić", "Nie wypełniono obowiązkowych pól", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_dodajOknoKlasyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoKlasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoKlasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoKlasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoKlasy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoKlasy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anulujOknoKlasyButton;
    private javax.swing.JLabel dodajNowaKlaseLabel;
    private javax.swing.JButton dodajOknoKlasyButton;
    private javax.swing.JLabel nazwaOknoKlasyLabel;
    private javax.swing.JTextField nazwaOknoKlasyTextField;
    private javax.swing.JLabel obowiazkoweNazwaLabel;
    private javax.swing.JLabel obowiazkoweProfilLabel;
    private javax.swing.JLabel obowiazkoweRokPowstaniaLabel;
    private javax.swing.JPanel oknoKlasyPanel;
    private javax.swing.JLabel profilOknoKlasyLabel;
    private javax.swing.JTextField profilOknoKlasyTextField;
    private javax.swing.JLabel rokPowstaniaOknoKlasyLabel;
    private javax.swing.JTextField rokPowstaniaOknoKlasyTextField;
    // End of variables declaration//GEN-END:variables
}
