/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DziennikElektroniczny.okna;

import DziennikElektroniczny.modele.KlasyComboBoxModel;
import DziennikElektroniczny.modele.ListaKlasModel;
import DziennikElektroniczny.modele.ListaNauczycieliModel;
import DziennikElektroniczny.modele.ListaPrzedmiotowModel;
import DziennikElektroniczny.modele.NauczycieleComboBoxModel;
import DziennikElektroniczny.modele.PrzedmiotyComboBoxModel;
import DziennikElektroniczny.modele.PrzydzialyTableModel;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author patry
 */
public class OknoListyPrzydzialow extends javax.swing.JFrame {

    /**
     * Creates new form OknoListyRealizacjiNauczania
     */
    private javax.swing.JFrame oknoAplikacji;
    private final Connection conn;
    private PrzydzialyTableModel listaPrzydzialowModel;
    private javax.swing.ComboBoxModel klasyComboBoxModel;
    private javax.swing.ComboBoxModel przedmiotyComboBoxModel;
    private javax.swing.ComboBoxModel nauczycieleComboBoxModel;

    public OknoListyPrzydzialow(javax.swing.JFrame oknoAplikacji, Connection connection) {
        conn = connection;
        this.oknoAplikacji = oknoAplikacji;
        initComponents();
        setVisible(true);

        ListaKlasModel listaKlasModel = new ListaKlasModel();
        String[] listaKlas = listaKlasModel.listaKlas(conn);
        klasyComboBoxModel = new KlasyComboBoxModel(listaKlas);
        klasyComboBox.setModel(klasyComboBoxModel);

        ListaPrzedmiotowModel listaPrzedmiotowModel = new ListaPrzedmiotowModel();
        String[] listaPrzedmiotow = listaPrzedmiotowModel.listaPrzedmiotow(conn);
        przedmiotyComboBoxModel = new PrzedmiotyComboBoxModel(listaPrzedmiotow);
        przedmiotyComboBox.setModel(przedmiotyComboBoxModel);

        ListaNauczycieliModel listaNauczycieliModel = new ListaNauczycieliModel();
        String[] listaNauczycieli = listaNauczycieliModel.listaNauczycieli(conn);
        nauczycieleComboBoxModel = new NauczycieleComboBoxModel(listaNauczycieli);
        nauczycieleComboBox.setModel(nauczycieleComboBoxModel);

        listaPrzydzialowModel = new PrzydzialyTableModel(conn,
                klasyComboBox.getSelectedItem().toString(),
                przedmiotyComboBox.getSelectedItem().toString(),
                nauczycieleComboBox.getSelectedItem().toString());
        listaPrzydzialowModel.fireTableDataChanged();
        listaPrzydzialowTable.setModel(listaPrzydzialowModel);
        listaPrzydzialowTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private OknoListyPrzydzialow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknoListyPrzydzialowPanel = new javax.swing.JPanel();
        listaPrzydzialowLabel = new javax.swing.JLabel();
        listaPrzydzialowScrollPane = new javax.swing.JScrollPane();
        listaPrzydzialowTable = new javax.swing.JTable();
        opcjePanel = new javax.swing.JPanel();
        dodajButton = new javax.swing.JButton();
        usunButton = new javax.swing.JButton();
        edytujButton = new javax.swing.JButton();
        wyjdzOknoListyPrzydzialowButton = new javax.swing.JButton();
        klasaLabel = new javax.swing.JLabel();
        klasyComboBox = new javax.swing.JComboBox<>();
        przedmiotLabel = new javax.swing.JLabel();
        przedmiotyComboBox = new javax.swing.JComboBox<>();
        nauczycielLabel = new javax.swing.JLabel();
        nauczycieleComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Przydział przedmiotów i nauczycieli");
        setLocation(new java.awt.Point(550, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        listaPrzydzialowLabel.setFont(new java.awt.Font("PT Serif", 1, 24)); // NOI18N
        listaPrzydzialowLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listaPrzydzialowLabel.setText("LISTA PRZYDZIAŁÓW");
        listaPrzydzialowLabel.setPreferredSize(new java.awt.Dimension(257, 30));

        listaPrzydzialowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listaPrzydzialowTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaPrzydzialowTableMousePressed(evt);
            }
        });
        listaPrzydzialowScrollPane.setViewportView(listaPrzydzialowTable);

        dodajButton.setText("DODAJ");
        dodajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajButtonActionPerformed(evt);
            }
        });

        usunButton.setText("USUŃ");
        usunButton.setEnabled(false);
        usunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunButtonActionPerformed(evt);
            }
        });

        edytujButton.setText("EDYTUJ");
        edytujButton.setEnabled(false);
        edytujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edytujButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcjePanelLayout = new javax.swing.GroupLayout(opcjePanel);
        opcjePanel.setLayout(opcjePanelLayout);
        opcjePanelLayout.setHorizontalGroup(
            opcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dodajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usunButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(edytujButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        opcjePanelLayout.setVerticalGroup(
            opcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcjePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dodajButton)
                .addGap(30, 30, 30)
                .addComponent(usunButton)
                .addGap(26, 26, 26)
                .addComponent(edytujButton)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        wyjdzOknoListyPrzydzialowButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wyjdzOknoListyPrzydzialowButton.setText("WYJDŹ");
        wyjdzOknoListyPrzydzialowButton.setPreferredSize(new java.awt.Dimension(100, 30));
        wyjdzOknoListyPrzydzialowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzOknoListyPrzydzialowButtonActionPerformed(evt);
            }
        });

        klasaLabel.setText("Klasa:");

        klasyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        klasyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klasyComboBoxActionPerformed(evt);
            }
        });

        przedmiotLabel.setText("Przedmiot:");

        przedmiotyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        przedmiotyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przedmiotyComboBoxActionPerformed(evt);
            }
        });

        nauczycielLabel.setText("Nauczyciel:");

        nauczycieleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nauczycieleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nauczycieleComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout oknoListyPrzydzialowPanelLayout = new javax.swing.GroupLayout(oknoListyPrzydzialowPanel);
        oknoListyPrzydzialowPanel.setLayout(oknoListyPrzydzialowPanelLayout);
        oknoListyPrzydzialowPanelLayout.setHorizontalGroup(
            oknoListyPrzydzialowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknoListyPrzydzialowPanelLayout.createSequentialGroup()
                .addGroup(oknoListyPrzydzialowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oknoListyPrzydzialowPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(listaPrzydzialowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(oknoListyPrzydzialowPanelLayout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(wyjdzOknoListyPrzydzialowButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(oknoListyPrzydzialowPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(oknoListyPrzydzialowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oknoListyPrzydzialowPanelLayout.createSequentialGroup()
                        .addComponent(listaPrzydzialowScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(opcjePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(oknoListyPrzydzialowPanelLayout.createSequentialGroup()
                        .addGroup(oknoListyPrzydzialowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(klasaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(przedmiotLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nauczycielLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(oknoListyPrzydzialowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nauczycieleComboBox, 0, 150, Short.MAX_VALUE)
                            .addComponent(klasyComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(przedmiotyComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );
        oknoListyPrzydzialowPanelLayout.setVerticalGroup(
            oknoListyPrzydzialowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknoListyPrzydzialowPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(listaPrzydzialowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(oknoListyPrzydzialowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(klasyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(klasaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(oknoListyPrzydzialowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(przedmiotyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(przedmiotLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(oknoListyPrzydzialowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nauczycielLabel)
                    .addComponent(nauczycieleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(oknoListyPrzydzialowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(opcjePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaPrzydzialowScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wyjdzOknoListyPrzydzialowButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoListyPrzydzialowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoListyPrzydzialowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        oknoAplikacji.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void wyjdzOknoListyPrzydzialowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzOknoListyPrzydzialowButtonActionPerformed
        oknoAplikacji.setEnabled(true);
        dispose();
    }//GEN-LAST:event_wyjdzOknoListyPrzydzialowButtonActionPerformed

    private void dodajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoPrzydzialu oknoPrzydzialu = new OknoPrzydzialu(this, conn, listaPrzydzialowModel, listaPrzydzialowTable, edytujButton, usunButton, "Dodaj nowy przydział",
                    klasyComboBox.getSelectedItem().toString(), przedmiotyComboBox.getSelectedItem().toString(), nauczycieleComboBox.getSelectedItem().toString());
        });
        setEnabled(false);
    }//GEN-LAST:event_dodajButtonActionPerformed

    private void listaPrzydzialowTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPrzydzialowTableMousePressed
        if (evt.getButton() == MouseEvent.BUTTON1) {
            edytujButton.setEnabled(true);
            usunButton.setEnabled(true);
        }
    }//GEN-LAST:event_listaPrzydzialowTableMousePressed

    private void edytujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edytujButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoPrzydzialu oknoPrzydzialu = new OknoPrzydzialu(this, conn, listaPrzydzialowModel, listaPrzydzialowTable, edytujButton, usunButton, "Edytuj wybrany przydział",
                    klasyComboBox.getSelectedItem().toString(), przedmiotyComboBox.getSelectedItem().toString(), nauczycieleComboBox.getSelectedItem().toString());
        });
        setEnabled(false);
    }//GEN-LAST:event_edytujButtonActionPerformed

    private void usunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunButtonActionPerformed
        listaPrzydzialowModel.deleteRow(listaPrzydzialowTable.getSelectedRow());
        listaPrzydzialowModel = new PrzydzialyTableModel(conn, klasyComboBox.getSelectedItem().toString(), przedmiotyComboBox.getSelectedItem().toString(), nauczycieleComboBox.getSelectedItem().toString());
        listaPrzydzialowModel.fireTableDataChanged();
        listaPrzydzialowTable.setModel(listaPrzydzialowModel);
        edytujButton.setEnabled(false);
        usunButton.setEnabled(false);
    }//GEN-LAST:event_usunButtonActionPerformed

    private void klasyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klasyComboBoxActionPerformed
        listaPrzydzialowModel = new PrzydzialyTableModel(conn, klasyComboBox.getSelectedItem().toString(), przedmiotyComboBox.getSelectedItem().toString(), nauczycieleComboBox.getSelectedItem().toString());
        listaPrzydzialowModel.fireTableDataChanged();
        listaPrzydzialowTable.setModel(listaPrzydzialowModel);
        edytujButton.setEnabled(false);
        usunButton.setEnabled(false);
    }//GEN-LAST:event_klasyComboBoxActionPerformed

    private void przedmiotyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przedmiotyComboBoxActionPerformed
        listaPrzydzialowModel = new PrzydzialyTableModel(conn, klasyComboBox.getSelectedItem().toString(), przedmiotyComboBox.getSelectedItem().toString(), nauczycieleComboBox.getSelectedItem().toString());
        listaPrzydzialowModel.fireTableDataChanged();
        listaPrzydzialowTable.setModel(listaPrzydzialowModel);
        edytujButton.setEnabled(false);
        usunButton.setEnabled(false);
    }//GEN-LAST:event_przedmiotyComboBoxActionPerformed

    private void nauczycieleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nauczycieleComboBoxActionPerformed
        listaPrzydzialowModel = new PrzydzialyTableModel(conn, klasyComboBox.getSelectedItem().toString(), przedmiotyComboBox.getSelectedItem().toString(), nauczycieleComboBox.getSelectedItem().toString());
        listaPrzydzialowModel.fireTableDataChanged();
        listaPrzydzialowTable.setModel(listaPrzydzialowModel);
        edytujButton.setEnabled(false);
        usunButton.setEnabled(false);
    }//GEN-LAST:event_nauczycieleComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoListyPrzydzialow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoListyPrzydzialow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoListyPrzydzialow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoListyPrzydzialow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoListyPrzydzialow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodajButton;
    private javax.swing.JButton edytujButton;
    private javax.swing.JLabel klasaLabel;
    private javax.swing.JComboBox<String> klasyComboBox;
    private javax.swing.JLabel listaPrzydzialowLabel;
    private javax.swing.JScrollPane listaPrzydzialowScrollPane;
    private javax.swing.JTable listaPrzydzialowTable;
    private javax.swing.JLabel nauczycielLabel;
    private javax.swing.JComboBox<String> nauczycieleComboBox;
    private javax.swing.JPanel oknoListyPrzydzialowPanel;
    private javax.swing.JPanel opcjePanel;
    private javax.swing.JLabel przedmiotLabel;
    private javax.swing.JComboBox<String> przedmiotyComboBox;
    private javax.swing.JButton usunButton;
    private javax.swing.JButton wyjdzOknoListyPrzydzialowButton;
    // End of variables declaration//GEN-END:variables
}
