/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DziennikElektroniczny;

import java.sql.*;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/**
 *
 * @author patry
 */
public class OknoListyKlas extends javax.swing.JFrame {

    /**
     * Creates new form OknoListyKlas
     */
    private javax.swing.JFrame oknoAplikacji;
    private final Connection conn;
    private ListaKlasModel listaKlasModel;

    public OknoListyKlas(javax.swing.JFrame oknoAplikacji, Connection connection) {
        conn = connection;
        this.oknoAplikacji = oknoAplikacji;
        initComponents();
        listaKlasModel = new ListaKlasModel(conn);
        listaKlasModel.fireTableDataChanged();
        listyTable.setModel(listaKlasModel);
        setVisible(true);
    }

    private OknoListyKlas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknoListPanel = new javax.swing.JPanel();
        wyjdzOknoListButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        listyScrollPane = new javax.swing.JScrollPane();
        listyTable = new javax.swing.JTable();
        opcjePanel = new javax.swing.JPanel();
        dodajKlaseButton = new javax.swing.JButton();
        usunKlaseButton = new javax.swing.JButton();
        edytujKlaseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista Klas");
        setLocation(new java.awt.Point(550, 200));
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        oknoListPanel.setMaximumSize(new java.awt.Dimension(900, 600));
        oknoListPanel.setMinimumSize(new java.awt.Dimension(900, 600));

        wyjdzOknoListButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wyjdzOknoListButton.setText("WYJDŹ");
        wyjdzOknoListButton.setPreferredSize(new java.awt.Dimension(100, 30));
        wyjdzOknoListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzOknoListButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("PT Serif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA KLAS");
        jLabel1.setPreferredSize(new java.awt.Dimension(70, 30));

        listyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listyScrollPane.setViewportView(listyTable);

        dodajKlaseButton.setText("Dodaj");
        dodajKlaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajKlaseButtonActionPerformed(evt);
            }
        });

        usunKlaseButton.setText("Usuń");
        usunKlaseButton.setEnabled(false);

        edytujKlaseButton.setText("Edytuj");
        edytujKlaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edytujKlaseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcjePanelLayout = new javax.swing.GroupLayout(opcjePanel);
        opcjePanel.setLayout(opcjePanelLayout);
        opcjePanelLayout.setHorizontalGroup(
            opcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dodajKlaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usunKlaseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(edytujKlaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        opcjePanelLayout.setVerticalGroup(
            opcjePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcjePanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(dodajKlaseButton)
                .addGap(18, 18, 18)
                .addComponent(usunKlaseButton)
                .addGap(18, 18, 18)
                .addComponent(edytujKlaseButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout oknoListPanelLayout = new javax.swing.GroupLayout(oknoListPanel);
        oknoListPanel.setLayout(oknoListPanelLayout);
        oknoListPanelLayout.setHorizontalGroup(
            oknoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoListPanelLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(oknoListPanelLayout.createSequentialGroup()
                .addGroup(oknoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oknoListPanelLayout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(wyjdzOknoListButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(oknoListPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(listyScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(opcjePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        oknoListPanelLayout.setVerticalGroup(
            oknoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoListPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(oknoListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcjePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(wyjdzOknoListButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        oknoAplikacji.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void wyjdzOknoListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzOknoListButtonActionPerformed
        oknoAplikacji.setEnabled(true);
        dispose();
    }//GEN-LAST:event_wyjdzOknoListButtonActionPerformed

    private void dodajKlaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajKlaseButtonActionPerformed
        SwingUtilities.invokeLater(() -> {
            OknoKlasy oknoKlasy = new OknoKlasy(this, conn, listaKlasModel, listyTable);
        });
        setEnabled(false);
    }//GEN-LAST:event_dodajKlaseButtonActionPerformed

    private void edytujKlaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edytujKlaseButtonActionPerformed

    }//GEN-LAST:event_edytujKlaseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoListyKlas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoListyKlas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoListyKlas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoListyKlas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoListyKlas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodajKlaseButton;
    private javax.swing.JButton edytujKlaseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane listyScrollPane;
    private javax.swing.JTable listyTable;
    private javax.swing.JPanel oknoListPanel;
    private javax.swing.JPanel opcjePanel;
    private javax.swing.JButton usunKlaseButton;
    private javax.swing.JButton wyjdzOknoListButton;
    // End of variables declaration//GEN-END:variables
}
