/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DziennikElektroniczny;

/**
 *
 * @author patry
 */
public class OknoPlanuLekcji extends javax.swing.JFrame {

    /**
     * Creates new form OknoPlanuLekcji
     */
    
    private javax.swing.JFrame oknoAplikacji;
    
    public OknoPlanuLekcji(javax.swing.JFrame oknoAplikacji) {
        initComponents();
        this.oknoAplikacji = oknoAplikacji;
        setVisible(true);
    }

    private OknoPlanuLekcji() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknoPlanuLekcjiPanel = new javax.swing.JPanel();
        wyjdzOknoPlanuLekcjiButton = new javax.swing.JButton();
        twojPlanLekcjiLabel = new javax.swing.JLabel();
        planLekcjiScrollPane = new javax.swing.JScrollPane();
        planLekcjiTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Plan lekcji");
        setLocation(new java.awt.Point(550, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        oknoPlanuLekcjiPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        oknoPlanuLekcjiPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        wyjdzOknoPlanuLekcjiButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wyjdzOknoPlanuLekcjiButton.setText("WYJDŹ");
        wyjdzOknoPlanuLekcjiButton.setFocusPainted(false);
        wyjdzOknoPlanuLekcjiButton.setMaximumSize(new java.awt.Dimension(100, 30));
        wyjdzOknoPlanuLekcjiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzOknoPlanuLekcjiButtonActionPerformed(evt);
            }
        });

        twojPlanLekcjiLabel.setFont(new java.awt.Font("PT Serif", 1, 24)); // NOI18N
        twojPlanLekcjiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        twojPlanLekcjiLabel.setText("TWÓJ PLAN LEKCJI");
        twojPlanLekcjiLabel.setMaximumSize(new java.awt.Dimension(250, 40));
        twojPlanLekcjiLabel.setMinimumSize(new java.awt.Dimension(225, 30));

        planLekcjiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        planLekcjiScrollPane.setViewportView(planLekcjiTable);

        javax.swing.GroupLayout oknoPlanuLekcjiPanelLayout = new javax.swing.GroupLayout(oknoPlanuLekcjiPanel);
        oknoPlanuLekcjiPanel.setLayout(oknoPlanuLekcjiPanelLayout);
        oknoPlanuLekcjiPanelLayout.setHorizontalGroup(
            oknoPlanuLekcjiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oknoPlanuLekcjiPanelLayout.createSequentialGroup()
                .addGroup(oknoPlanuLekcjiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oknoPlanuLekcjiPanelLayout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(wyjdzOknoPlanuLekcjiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(oknoPlanuLekcjiPanelLayout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(twojPlanLekcjiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(oknoPlanuLekcjiPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(planLekcjiScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        oknoPlanuLekcjiPanelLayout.setVerticalGroup(
            oknoPlanuLekcjiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoPlanuLekcjiPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(twojPlanLekcjiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(planLekcjiScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wyjdzOknoPlanuLekcjiButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoPlanuLekcjiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoPlanuLekcjiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        oknoAplikacji.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void wyjdzOknoPlanuLekcjiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzOknoPlanuLekcjiButtonActionPerformed
        oknoAplikacji.setEnabled(true);
        dispose();
    }//GEN-LAST:event_wyjdzOknoPlanuLekcjiButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoPlanuLekcji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoPlanuLekcji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoPlanuLekcji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoPlanuLekcji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoPlanuLekcji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel oknoPlanuLekcjiPanel;
    private javax.swing.JScrollPane planLekcjiScrollPane;
    private javax.swing.JTable planLekcjiTable;
    private javax.swing.JLabel twojPlanLekcjiLabel;
    private javax.swing.JButton wyjdzOknoPlanuLekcjiButton;
    // End of variables declaration//GEN-END:variables
}
