/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DziennikElektroniczny;

/**
 *
 * @author patry
 */
public class OknoNieobecnosci extends javax.swing.JFrame {

    /**
     * Creates new form OknoNieobecnosci
     */
    
    private javax.swing.JFrame oknoAplikacji;
    
    public OknoNieobecnosci(javax.swing.JFrame oknoAplikacji) {
        initComponents();
        this.oknoAplikacji = oknoAplikacji;
        setVisible(true);
    }

    private OknoNieobecnosci() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oknoNieobecnosciPanel = new javax.swing.JPanel();
        wyjdzOknoNieobecnosciButton = new javax.swing.JButton();
        twojeNieobecnosciLabel = new javax.swing.JLabel();
        nieobecnosciScrollPane = new javax.swing.JScrollPane();
        nieobecnosciTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nieobecności");
        setLocation(new java.awt.Point(550, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        oknoNieobecnosciPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        wyjdzOknoNieobecnosciButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        wyjdzOknoNieobecnosciButton.setText("WYJDŹ");
        wyjdzOknoNieobecnosciButton.setFocusPainted(false);
        wyjdzOknoNieobecnosciButton.setPreferredSize(new java.awt.Dimension(100, 30));
        wyjdzOknoNieobecnosciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzOknoNieobecnosciButtonActionPerformed(evt);
            }
        });

        twojeNieobecnosciLabel.setFont(new java.awt.Font("PT Serif", 1, 24)); // NOI18N
        twojeNieobecnosciLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        twojeNieobecnosciLabel.setText("TWOJE NIEOBECNOŚCI");
        twojeNieobecnosciLabel.setPreferredSize(new java.awt.Dimension(300, 30));

        nieobecnosciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        nieobecnosciScrollPane.setViewportView(nieobecnosciTable);

        javax.swing.GroupLayout oknoNieobecnosciPanelLayout = new javax.swing.GroupLayout(oknoNieobecnosciPanel);
        oknoNieobecnosciPanel.setLayout(oknoNieobecnosciPanelLayout);
        oknoNieobecnosciPanelLayout.setHorizontalGroup(
            oknoNieobecnosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoNieobecnosciPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wyjdzOknoNieobecnosciButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
            .addGroup(oknoNieobecnosciPanelLayout.createSequentialGroup()
                .addGroup(oknoNieobecnosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oknoNieobecnosciPanelLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(twojeNieobecnosciLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(oknoNieobecnosciPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(nieobecnosciScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        oknoNieobecnosciPanelLayout.setVerticalGroup(
            oknoNieobecnosciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oknoNieobecnosciPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(twojeNieobecnosciLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(nieobecnosciScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wyjdzOknoNieobecnosciButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoNieobecnosciPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oknoNieobecnosciPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wyjdzOknoNieobecnosciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzOknoNieobecnosciButtonActionPerformed
        oknoAplikacji.setEnabled(true);
        dispose();
    }//GEN-LAST:event_wyjdzOknoNieobecnosciButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        oknoAplikacji.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoNieobecnosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoNieobecnosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoNieobecnosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoNieobecnosci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoNieobecnosci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane nieobecnosciScrollPane;
    private javax.swing.JTable nieobecnosciTable;
    private javax.swing.JPanel oknoNieobecnosciPanel;
    private javax.swing.JLabel twojeNieobecnosciLabel;
    private javax.swing.JButton wyjdzOknoNieobecnosciButton;
    // End of variables declaration//GEN-END:variables
}
