/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DziennikElektroniczny;

import java.awt.Dialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author patry
 */
public class OknoAplikacji extends javax.swing.JFrame {

    /**
     * Creates new form OknoLogowania
     */
    public OknoAplikacji() {
        initComponents();
        trybUczniaPanel.setVisible(false);
        trybRodzicaPanel.setVisible(false);
        trybNauczycielaPanel.setVisible(false);
        trybDyrektoraPanel.setVisible(false);
        logowaniePanel.setVisible(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPanel = new javax.swing.JPanel();
        uczenButton = new javax.swing.JButton();
        rodzicButton = new javax.swing.JButton();
        nauczycielButton = new javax.swing.JButton();
        dyrektorButton = new javax.swing.JButton();
        zamknijOknoLogowaniaButton = new javax.swing.JButton();
        dziennikElektronicznyLabel = new javax.swing.JLabel();
        logowaniePanel = new javax.swing.JPanel();
        panelLogowanieLabel = new javax.swing.JLabel();
        nazwaUzytkownikaLogowanieLabel = new javax.swing.JLabel();
        nazwaUzytkownikaLogowanieTextField = new javax.swing.JTextField();
        hasloLogowanieLabel = new javax.swing.JLabel();
        hasloLogowaniePasswordField = new javax.swing.JPasswordField();
        zalogujLogowanieButton = new javax.swing.JButton();
        wsteczLogowanieButton = new javax.swing.JButton();
        trybUczniaPanel = new javax.swing.JPanel();
        wyjdzTrybUczniaButton = new javax.swing.JButton();
        trybUczniaLabel = new javax.swing.JLabel();
        trybRodzicaPanel = new javax.swing.JPanel();
        wyjdzTrybRodzicaButton = new javax.swing.JButton();
        trybRodzicaLabel = new javax.swing.JLabel();
        trybNauczycielaPanel = new javax.swing.JPanel();
        wyjdzTrybNauczycielaButton = new javax.swing.JButton();
        trybNauczycielaLabel = new javax.swing.JLabel();
        trybDyrektoraPanel = new javax.swing.JPanel();
        wyjdzTrybDyrektoraButton = new javax.swing.JButton();
        trybDyrektoraLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dziennik Elektroniczny");
        setBackground(new java.awt.Color(51, 51, 255));
        setLocation(new java.awt.Point(700, 200));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setName("oknoLogowania"); // NOI18N
        setResizable(false);

        uczenButton.setText("UCZEŃ");
        uczenButton.setFocusPainted(false);
        uczenButton.setName("uczenButton"); // NOI18N
        uczenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uczenButtonActionPerformed(evt);
            }
        });

        rodzicButton.setText("RODZIC");
        rodzicButton.setFocusPainted(false);
        rodzicButton.setName("rodzicButton"); // NOI18N
        rodzicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rodzicButtonActionPerformed(evt);
            }
        });

        nauczycielButton.setText("NAUCZYCIEL");
        nauczycielButton.setFocusPainted(false);
        nauczycielButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nauczycielButton.setName("uczenButton"); // NOI18N
        nauczycielButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nauczycielButtonActionPerformed(evt);
            }
        });

        dyrektorButton.setText("DYREKTOR");
        dyrektorButton.setFocusPainted(false);
        dyrektorButton.setName("dyrektorButton"); // NOI18N
        dyrektorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dyrektorButtonActionPerformed(evt);
            }
        });

        zamknijOknoLogowaniaButton.setText("Zamknij");
        zamknijOknoLogowaniaButton.setFocusPainted(false);
        zamknijOknoLogowaniaButton.setPreferredSize(new java.awt.Dimension(80, 25));
        zamknijOknoLogowaniaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamknijOknoLogowaniaButtonActionPerformed(evt);
            }
        });

        dziennikElektronicznyLabel.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        dziennikElektronicznyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dziennikElektronicznyLabel.setText("Dziennik Elektroniczny");
        dziennikElektronicznyLabel.setToolTipText("");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(dziennikElektronicznyLabel)
                .addGap(65, 65, 65))
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dyrektorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(nauczycielButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(rodzicButton, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(uczenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(zamknijOknoLogowaniaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(dziennikElektronicznyLabel)
                .addGap(83, 83, 83)
                .addComponent(uczenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rodzicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nauczycielButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dyrektorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(zamknijOknoLogowaniaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        logowaniePanel.setMaximumSize(new java.awt.Dimension(600, 600));
        logowaniePanel.setPreferredSize(new java.awt.Dimension(600, 600));

        panelLogowanieLabel.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        panelLogowanieLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelLogowanieLabel.setText("panel ucznia");
        panelLogowanieLabel.setMaximumSize(new java.awt.Dimension(250, 30));
        panelLogowanieLabel.setMinimumSize(new java.awt.Dimension(250, 30));
        panelLogowanieLabel.setPreferredSize(new java.awt.Dimension(250, 30));

        nazwaUzytkownikaLogowanieLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nazwaUzytkownikaLogowanieLabel.setText("Nazwa użytkownika:");

        nazwaUzytkownikaLogowanieTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        hasloLogowanieLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hasloLogowanieLabel.setText("Hasło:");

        hasloLogowaniePasswordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        zalogujLogowanieButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zalogujLogowanieButton.setText("Zaloguj");
        zalogujLogowanieButton.setFocusPainted(false);
        zalogujLogowanieButton.setPreferredSize(new java.awt.Dimension(100, 30));
        zalogujLogowanieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zalogujLogowanieButtonActionPerformed(evt);
            }
        });

        wsteczLogowanieButton.setText("Wstecz");
        wsteczLogowanieButton.setFocusPainted(false);
        wsteczLogowanieButton.setPreferredSize(new java.awt.Dimension(80, 25));
        wsteczLogowanieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wsteczLogowanieButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logowaniePanelLayout = new javax.swing.GroupLayout(logowaniePanel);
        logowaniePanel.setLayout(logowaniePanelLayout);
        logowaniePanelLayout.setHorizontalGroup(
            logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logowaniePanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nazwaUzytkownikaLogowanieLabel)
                    .addComponent(hasloLogowanieLabel))
                .addGap(18, 18, 18)
                .addGroup(logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasloLogowaniePasswordField)
                    .addComponent(nazwaUzytkownikaLogowanieTextField))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logowaniePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(zalogujLogowanieButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(logowaniePanelLayout.createSequentialGroup()
                .addGroup(logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logowaniePanelLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(wsteczLogowanieButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(logowaniePanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(panelLogowanieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        logowaniePanelLayout.setVerticalGroup(
            logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logowaniePanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(panelLogowanieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addGroup(logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwaUzytkownikaLogowanieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazwaUzytkownikaLogowanieLabel))
                .addGap(34, 34, 34)
                .addGroup(logowaniePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasloLogowaniePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasloLogowanieLabel))
                .addGap(44, 44, 44)
                .addComponent(zalogujLogowanieButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(wsteczLogowanieButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        wyjdzTrybUczniaButton.setText("Wyjdź");
        wyjdzTrybUczniaButton.setPreferredSize(new java.awt.Dimension(80, 25));
        wyjdzTrybUczniaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzTrybUczniaButtonActionPerformed(evt);
            }
        });

        trybUczniaLabel.setText("Tryb Ucznia");

        javax.swing.GroupLayout trybUczniaPanelLayout = new javax.swing.GroupLayout(trybUczniaPanel);
        trybUczniaPanel.setLayout(trybUczniaPanelLayout);
        trybUczniaPanelLayout.setHorizontalGroup(
            trybUczniaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybUczniaPanelLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(wyjdzTrybUczniaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
            .addGroup(trybUczniaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(trybUczniaPanelLayout.createSequentialGroup()
                    .addGap(266, 266, 266)
                    .addComponent(trybUczniaLabel)
                    .addContainerGap(267, Short.MAX_VALUE)))
        );
        trybUczniaPanelLayout.setVerticalGroup(
            trybUczniaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybUczniaPanelLayout.createSequentialGroup()
                .addContainerGap(562, Short.MAX_VALUE)
                .addComponent(wyjdzTrybUczniaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(trybUczniaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(trybUczniaPanelLayout.createSequentialGroup()
                    .addGap(292, 292, 292)
                    .addComponent(trybUczniaLabel)
                    .addContainerGap(292, Short.MAX_VALUE)))
        );

        trybRodzicaPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        wyjdzTrybRodzicaButton.setText("Wyjdź");
        wyjdzTrybRodzicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzTrybRodzicaButtonActionPerformed(evt);
            }
        });

        trybRodzicaLabel.setText("Tryb Rodzica");

        javax.swing.GroupLayout trybRodzicaPanelLayout = new javax.swing.GroupLayout(trybRodzicaPanel);
        trybRodzicaPanel.setLayout(trybRodzicaPanelLayout);
        trybRodzicaPanelLayout.setHorizontalGroup(
            trybRodzicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybRodzicaPanelLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(trybRodzicaLabel)
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(trybRodzicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(trybRodzicaPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(wyjdzTrybRodzicaButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        trybRodzicaPanelLayout.setVerticalGroup(
            trybRodzicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybRodzicaPanelLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(trybRodzicaLabel)
                .addContainerGap(447, Short.MAX_VALUE))
            .addGroup(trybRodzicaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(trybRodzicaPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(wyjdzTrybRodzicaButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        trybNauczycielaPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        wyjdzTrybNauczycielaButton.setText("Wyjdź");
        wyjdzTrybNauczycielaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzTrybNauczycielaButtonActionPerformed(evt);
            }
        });

        trybNauczycielaLabel.setText("Tryb Nauczyciela");

        javax.swing.GroupLayout trybNauczycielaPanelLayout = new javax.swing.GroupLayout(trybNauczycielaPanel);
        trybNauczycielaPanel.setLayout(trybNauczycielaPanelLayout);
        trybNauczycielaPanelLayout.setHorizontalGroup(
            trybNauczycielaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybNauczycielaPanelLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(wyjdzTrybNauczycielaButton)
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(trybNauczycielaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(trybNauczycielaPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybNauczycielaLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        trybNauczycielaPanelLayout.setVerticalGroup(
            trybNauczycielaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trybNauczycielaPanelLayout.createSequentialGroup()
                .addContainerGap(545, Short.MAX_VALUE)
                .addComponent(wyjdzTrybNauczycielaButton)
                .addGap(30, 30, 30))
            .addGroup(trybNauczycielaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(trybNauczycielaPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybNauczycielaLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        wyjdzTrybDyrektoraButton.setText("Wyjdź");
        wyjdzTrybDyrektoraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzTrybDyrektoraButtonActionPerformed(evt);
            }
        });

        trybDyrektoraLabel.setText("Tryb Dyrektora");

        javax.swing.GroupLayout trybDyrektoraPanelLayout = new javax.swing.GroupLayout(trybDyrektoraPanel);
        trybDyrektoraPanel.setLayout(trybDyrektoraPanelLayout);
        trybDyrektoraPanelLayout.setHorizontalGroup(
            trybDyrektoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trybDyrektoraPanelLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(wyjdzTrybDyrektoraButton)
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(trybDyrektoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(trybDyrektoraPanelLayout.createSequentialGroup()
                    .addGap(0, 257, Short.MAX_VALUE)
                    .addComponent(trybDyrektoraLabel)
                    .addGap(0, 258, Short.MAX_VALUE)))
        );
        trybDyrektoraPanelLayout.setVerticalGroup(
            trybDyrektoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trybDyrektoraPanelLayout.createSequentialGroup()
                .addContainerGap(453, Short.MAX_VALUE)
                .addComponent(wyjdzTrybDyrektoraButton)
                .addGap(122, 122, 122))
            .addGroup(trybDyrektoraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(trybDyrektoraPanelLayout.createSequentialGroup()
                    .addGap(0, 292, Short.MAX_VALUE)
                    .addComponent(trybDyrektoraLabel)
                    .addGap(0, 292, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybUczniaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybRodzicaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybNauczycielaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybDyrektoraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(logowaniePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybUczniaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybRodzicaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybNauczycielaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(trybDyrektoraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(logowaniePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void zStartDoLogowanie(String tekst) {
        startPanel.setVisible(false);
        panelLogowanieLabel.setText(tekst);
        nazwaUzytkownikaLogowanieTextField.setText("");
        hasloLogowaniePasswordField.setText("");
        logowaniePanel.setVisible(true);
    }
    
    private void uczenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uczenButtonActionPerformed
        zStartDoLogowanie("panel ucznia");
    }//GEN-LAST:event_uczenButtonActionPerformed

    private void rodzicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rodzicButtonActionPerformed
        zStartDoLogowanie("panel rodzica");
    }//GEN-LAST:event_rodzicButtonActionPerformed

    private void nauczycielButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nauczycielButtonActionPerformed
        zStartDoLogowanie("panel nauczyciela");
    }//GEN-LAST:event_nauczycielButtonActionPerformed

    private void dyrektorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dyrektorButtonActionPerformed
        zStartDoLogowanie("panel dyrektora");
    }//GEN-LAST:event_dyrektorButtonActionPerformed

    private void zamknijOknoLogowaniaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamknijOknoLogowaniaButtonActionPerformed
        dispose();
    }//GEN-LAST:event_zamknijOknoLogowaniaButtonActionPerformed

    private void wyjdzTrybUczniaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzTrybUczniaButtonActionPerformed
        trybUczniaPanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_wyjdzTrybUczniaButtonActionPerformed

    private void wyjdzTrybRodzicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzTrybRodzicaButtonActionPerformed
        trybRodzicaPanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_wyjdzTrybRodzicaButtonActionPerformed

    private void wyjdzTrybNauczycielaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzTrybNauczycielaButtonActionPerformed
        trybNauczycielaPanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_wyjdzTrybNauczycielaButtonActionPerformed

    private void wyjdzTrybDyrektoraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzTrybDyrektoraButtonActionPerformed
        trybDyrektoraPanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_wyjdzTrybDyrektoraButtonActionPerformed

    private void zalogujLogowanieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zalogujLogowanieButtonActionPerformed
        if (panelLogowanieLabel.getText().equals("panel ucznia") && nazwaUzytkownikaLogowanieTextField.getText().equals("uczen") && hasloLogowaniePasswordField.getText().equals("uczen")) {
            logowaniePanel.setVisible(false);
            trybUczniaPanel.setVisible(true);
        } else if ((panelLogowanieLabel.getText().equals("panel rodzica") && nazwaUzytkownikaLogowanieTextField.getText().equals("rodzic") && hasloLogowaniePasswordField.getText().equals("rodzic"))) {
            logowaniePanel.setVisible(false);
            trybRodzicaPanel.setVisible(true);
        } else if ((panelLogowanieLabel.getText().equals("panel nauczyciela") && nazwaUzytkownikaLogowanieTextField.getText().equals("nauczyciel") && hasloLogowaniePasswordField.getText().equals("nauczyciel"))) {
            logowaniePanel.setVisible(false);
            trybNauczycielaPanel.setVisible(true);
        } else if ((panelLogowanieLabel.getText().equals("panel dyrektora") && nazwaUzytkownikaLogowanieTextField.getText().equals("dyrektor") && hasloLogowaniePasswordField.getText().equals("dyrektor"))) {
            logowaniePanel.setVisible(false);
            trybDyrektoraPanel.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "ERROR", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_zalogujLogowanieButtonActionPerformed

    private void wsteczLogowanieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wsteczLogowanieButtonActionPerformed
        logowaniePanel.setVisible(false);
        startPanel.setVisible(true);
    }//GEN-LAST:event_wsteczLogowanieButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoAplikacji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoAplikacji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dyrektorButton;
    private javax.swing.JLabel dziennikElektronicznyLabel;
    private javax.swing.JLabel hasloLogowanieLabel;
    private javax.swing.JPasswordField hasloLogowaniePasswordField;
    private javax.swing.JPanel logowaniePanel;
    private javax.swing.JButton nauczycielButton;
    private javax.swing.JLabel nazwaUzytkownikaLogowanieLabel;
    private javax.swing.JTextField nazwaUzytkownikaLogowanieTextField;
    private javax.swing.JLabel panelLogowanieLabel;
    private javax.swing.JButton rodzicButton;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLabel trybDyrektoraLabel;
    private javax.swing.JPanel trybDyrektoraPanel;
    private javax.swing.JLabel trybNauczycielaLabel;
    private javax.swing.JPanel trybNauczycielaPanel;
    private javax.swing.JLabel trybRodzicaLabel;
    private javax.swing.JPanel trybRodzicaPanel;
    private javax.swing.JLabel trybUczniaLabel;
    private javax.swing.JPanel trybUczniaPanel;
    private javax.swing.JButton uczenButton;
    private javax.swing.JButton wsteczLogowanieButton;
    private javax.swing.JButton wyjdzTrybDyrektoraButton;
    private javax.swing.JButton wyjdzTrybNauczycielaButton;
    private javax.swing.JButton wyjdzTrybRodzicaButton;
    private javax.swing.JButton wyjdzTrybUczniaButton;
    private javax.swing.JButton zalogujLogowanieButton;
    private javax.swing.JButton zamknijOknoLogowaniaButton;
    // End of variables declaration//GEN-END:variables
}
